services:
    payments.app:
        container_name: '${APP_SERVICE}'
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
        networks:
            - payments_osmisog_network
    mysql:
        container_name: 'db-payments-app'
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            # MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-payments-app:/var/lib/mysql'
            # - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - payments_osmisog_network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    nginx:
        container_name: 'nginx-payments-app'
        restart: always
        image: 'nginx:1.25.2-alpine'
        ports:
            - 80:80
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - payments.app
        networks:
            - payments_osmisog_network
networks:
    payments_osmisog_network:
        driver: bridge
volumes:
    mysql-payments-app:
